import type { IncomingHttpHeaders } from "http";
import type { Config } from "@/node/config";
import type { AIService } from "@/node/services/aiService";
import type { ProjectService } from "@/node/services/projectService";
import type { MinionService } from "@/node/services/minionService";
import type { LatticeGovernorOauthService } from "@/node/services/latticeGovernorOauthService";
import type { CodexOauthService } from "@/node/services/codexOauthService";
import type { CopilotOauthService } from "@/node/services/copilotOauthService";
import type { AnthropicOauthService } from "@/node/services/anthropicOauthService";
import type { ProviderService } from "@/node/services/providerService";
import type { TerminalService } from "@/node/services/terminalService";
import type { EditorService } from "@/node/services/editorService";
import type { WindowService } from "@/node/services/windowService";
import type { UpdateService } from "@/node/services/updateService";
import type { TokenizerService } from "@/node/services/tokenizerService";
import type { ServerService } from "@/node/services/serverService";
import type { MenuEventService } from "@/node/services/menuEventService";
import type { VoiceService } from "@/node/services/voiceService";
import type { MCPConfigService } from "@/node/services/mcpConfigService";
import type { McpOauthService } from "@/node/services/mcpOauthService";
import type { ExperimentsService } from "@/node/services/experimentsService";
import type { MinionMcpOverridesService } from "@/node/services/minionMcpOverridesService";
import type { MCPServerManager } from "@/node/services/mcpServerManager";
import type { TelemetryService } from "@/node/services/telemetryService";
import type { SigningService } from "@/node/services/signingService";
import type { FeatureFlagService } from "@/node/services/featureFlagService";
import type { SessionTimingService } from "@/node/services/sessionTimingService";
import type { SessionUsageService } from "@/node/services/sessionUsageService";
import type { TaskService } from "@/node/services/taskService";
import type { PolicyService } from "@/node/services/policyService";
import type { LatticeService } from "@/node/services/latticeService";
import type { ServerAuthService } from "@/node/services/serverAuthService";
import type { SshPromptService } from "@/node/services/sshPromptService";
import type { AnalyticsService } from "@/node/services/analytics/analyticsService";
import type { KanbanService } from "@/node/services/kanbanService";
import type { ExoService } from "@/node/services/exoService";
import type { SchedulerService } from "@/node/services/schedulerService";
import type { SyncService } from "@/node/services/syncService";
import type { InboxService } from "@/node/services/inboxService";

export interface ORPCContext {
  config: Config;
  aiService: AIService;
  projectService: ProjectService;
  minionService: MinionService;
  taskService: TaskService;
  providerService: ProviderService;
  latticeGovernorOauthService: LatticeGovernorOauthService;
  codexOauthService: CodexOauthService;
  copilotOauthService: CopilotOauthService;
  anthropicOauthService: AnthropicOauthService;
  terminalService: TerminalService;
  editorService: EditorService;
  windowService: WindowService;
  updateService: UpdateService;
  tokenizerService: TokenizerService;
  serverService: ServerService;
  menuEventService: MenuEventService;
  voiceService: VoiceService;
  mcpConfigService: MCPConfigService;
  mcpOauthService: McpOauthService;
  minionMcpOverridesService: MinionMcpOverridesService;
  mcpServerManager: MCPServerManager;
  featureFlagService: FeatureFlagService;
  sessionTimingService: SessionTimingService;
  telemetryService: TelemetryService;
  experimentsService: ExperimentsService;
  sessionUsageService: SessionUsageService;
  policyService: PolicyService;
  signingService: SigningService;
  latticeService: LatticeService;
  serverAuthService: ServerAuthService;
  sshPromptService: SshPromptService;
  analyticsService: AnalyticsService;
  kanbanService: KanbanService;
  exoService: ExoService;
  schedulerService: SchedulerService;
  syncService: SyncService;
  inboxService: InboxService;
  headers?: IncomingHttpHeaders;
}
